### ISSUE TITLE
Need some example code

### ISSUE THREAD

**Issue by Gliba** [graker/blogarchive#1]
Can you provide some example code how to implement plugin with blog?

**Comment by graker** [comment]
Hi
I'm not sure I understand the issue. Could you please expand on what kind of example you are looking for?

**Comment by Gliba** [comment]
How to create page with year? Year in slug or title or ...

**Comment by graker** [comment]
Thanks for clarification.
You create a page with :year, :month and :day in path, like this: `/news/:year/:month?/:day?`
Then you type `year`, `month` and `day` in corresponding blogArchive component options.

**Comment by Gliba** [comment]
Yep. NIce plugin. Ty
