### ISSUE TITLE
Why it is not on the Marketplace?

### ISSUE THREAD

**Issue by GinoPane** [graker/blogarchive#4]
Hi!
Is there any reason why this plugin wasn't published to the Marketplace?

**Comment by graker** [comment]
Hi @GinoPane,

I wasn't planning on publishing it initially. So I just put in stuff that is not needed to most users, like Typofilter integration, or Drupal 6 migration helper, CarbonLocale config or other commands unrelated to this plugin title. I used all that stuff to migrate my blog from Drupal.
